#!/usr/bin/env bash
set -Eeuo pipefail

export KERNEL_VERSION=6.8.9
export BUSYBOX_VERSION=1.32.0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="$SCRIPT_DIR/data"
ROOTFS_DIR="$DATA_DIR/rootfs"
MODULE_DIR="$DATA_DIR/src"
TOOLS_DIR="$DATA_DIR/tools"
LOG_DIR="$SCRIPT_DIR/log"
RUNTIME_KERNEL_IMAGE="$SCRIPT_DIR/bzImage"
RUNTIME_INITRAMFS="$SCRIPT_DIR/initramfs.cpio.gz"
RUNTIME_VMLINUX="$SCRIPT_DIR/vmlinux"
TRASH_GADGETS_FILE="$TOOLS_DIR/trash_gadgets"
TRASH_GADGETS_STAMP="$SCRIPT_DIR/.trash_gadgets.sha256"
cd "$SCRIPT_DIR"

if [ "$(uname -s)" != "Linux" ]; then
  echo "[-] This project builds on Linux only." >&2
  exit 1
fi

mkdir -p "$LOG_DIR"
BUILD_LOG="$LOG_DIR/build-$(date -u +%Y%m%dT%H%M%SZ)-$$.log"
exec 3>&1 4>&2
exec > >(tee -a "$BUILD_LOG")
log_stdout_pid=$!
exec 2> >(tee -a "$BUILD_LOG" >&2)
log_stderr_pid=$!

finish_logging() {
  local status="$1"
  exec 1>&3 2>&4
  wait "$log_stdout_pid" "$log_stderr_pid" || true
  exec 3>&- 4>&-
  exit "$status"
}

finish_logging_on_exit() {
  local status=$?
  trap - EXIT
  finish_logging "$status"
}
trap finish_logging_on_exit EXIT

echo "[+] Build log: $BUILD_LOG"

if [ ! -f "$TRASH_GADGETS_FILE" ]; then
  echo "[-] Missing gadget source: $TRASH_GADGETS_FILE" >&2
  exit 1
fi
TRASH_GADGETS_HASH="$(sha256sum "$TRASH_GADGETS_FILE" | awk '{print $1}')"

trash_gadgets_are_current() {
  [ -f "$TRASH_GADGETS_STAMP" ] && \
    [ "$(awk 'NR == 1 { print $1 }' "$TRASH_GADGETS_STAMP")" = "$TRASH_GADGETS_HASH" ]
}

# The input file intentionally stays simple: its non-comment lines are GNU
# assembler instructions in Intel syntax. Keep the code in a standalone
# assembly object so the compiler cannot insert a prologue or instrumentation
# between the requested instructions.
install_trash_gadgets() {
  local kernel_dir="$1"
  local source_file="$kernel_dir/arch/x86/kernel/pwn_college_trash_gadgets.S"
  local makefile="$kernel_dir/arch/x86/kernel/Makefile"
  local temporary_source="${source_file}.part"

  TRASH_GADGETS_CHANGED=0
  {
    cat <<'EOF'
/* Auto-generated from data/tools/trash_gadgets. Do not edit this file. */
	.text
	.intel_syntax noprefix
	.balign 16
	.global pwn_college_trash_gadgets
	.type pwn_college_trash_gadgets, @function
pwn_college_trash_gadgets:
EOF
    while IFS= read -r line || [ -n "$line" ]; do
      line="${line#"${line%%[![:space:]]*}"}"
      case "$line" in
        ''|'#'*) continue ;;
      esac
      printf '\t%s\n' "$line"
    done < "$TRASH_GADGETS_FILE"
    cat <<'EOF'
	.size pwn_college_trash_gadgets, . - pwn_college_trash_gadgets
	.att_syntax prefix
EOF
  } > "$temporary_source"

  if [ -f "$source_file" ] && cmp -s "$temporary_source" "$source_file"; then
    rm -f -- "$temporary_source"
  else
    mv -- "$temporary_source" "$source_file"
    TRASH_GADGETS_CHANGED=1
  fi

  if ! grep -Fqx 'obj-y += pwn_college_trash_gadgets.o' "$makefile"; then
    {
      printf '\n# Locally configured teaching/CTF ROP gadgets.\n'
      printf 'obj-y += pwn_college_trash_gadgets.o\n'
    } >> "$makefile"
    TRASH_GADGETS_CHANGED=1
  fi
}

JOBS="${JOBS:-2}"
if [ -z "${BUILD_DIR:-}" ]; then
  # A project below /mnt/<drive> is normally on NTFS/FAT, where the kernel
  # tree cannot be built safely because source names may differ only by case.
  # Keep its real source/build tree on the Linux filesystem instead.
  case "$SCRIPT_DIR" in
    /mnt/[a-z]/*)
      project_id="$(printf '%s' "$SCRIPT_DIR" | sha256sum | cut -c1-16)"
      BUILD_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/pwnkernel/$project_id"
      ;;
    *) BUILD_DIR="$DATA_DIR/build" ;;
  esac
fi
mkdir -p "$BUILD_DIR"
BUILD_DIR="$(cd "$BUILD_DIR" && pwd)"
echo "[+] Build directory: $BUILD_DIR"
BUILD_DIR="$BUILD_DIR" bash "$SCRIPT_DIR/clean.sh" before-build

#
# dependencies
#
if [ "${SKIP_DEPS:-0}" != "1" ]; then
  echo "[+] Checking / installing dependencies..."
  if command -v apt-get >/dev/null 2>&1; then
    if [ "$(id -u)" -eq 0 ]; then
      apt-get -q update
      apt-get -q install -y bc bison flex libelf-dev cpio build-essential libssl-dev qemu-system-x86 wget
    elif command -v sudo >/dev/null 2>&1; then
      sudo apt-get -q update
      sudo apt-get -q install -y bc bison flex libelf-dev cpio build-essential libssl-dev qemu-system-x86 wget
    else
      echo "[-] apt-get is available, but sudo is not. Install dependencies manually or run with SKIP_DEPS=1 in the Docker image." >&2
      exit 1
    fi
  else
    echo "[-] apt-get is not available. Run this script in Linux/WSL or use the Docker wrapper." >&2
    exit 1
  fi
else
  echo "[+] Skipping dependency installation (SKIP_DEPS=1)."
fi

cd "$BUILD_DIR"

#
# linux kernel
#

echo "[+] Preparing kernel..."
if [ ! -d "linux-$KERNEL_VERSION" ] && [ ! -f "linux-$KERNEL_VERSION.tar.gz" ]; then
  wget -c -O linux-$KERNEL_VERSION.tar.gz.part https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL_VERSION.tar.gz
  mv linux-$KERNEL_VERSION.tar.gz.part linux-$KERNEL_VERSION.tar.gz
elif [ -f "linux-$KERNEL_VERSION.tar.gz" ]; then
  echo "[+] Using cached linux-$KERNEL_VERSION.tar.gz."
else
  echo "[+] Using existing kernel source tree."
fi
[ -e linux-$KERNEL_VERSION ] || tar xzf linux-$KERNEL_VERSION.tar.gz

install_trash_gadgets "linux-$KERNEL_VERSION"

kernel_security_config_ok() {
  grep -qx 'CONFIG_INIT_STACK_NONE=y' "linux-$KERNEL_VERSION/.config" 2>/dev/null && \
    grep -qx '# CONFIG_VMAP_STACK is not set' "linux-$KERNEL_VERSION/.config" 2>/dev/null
}

if [ "${FORCE_KERNEL_REBUILD:-0}" != "1" ] && \
  [ -f linux-$KERNEL_VERSION/arch/x86/boot/bzImage ] && \
  [ -f linux-$KERNEL_VERSION/vmlinux ] && \
  [ -f linux-$KERNEL_VERSION/Module.symvers ] && \
  [ "$TRASH_GADGETS_CHANGED" = "0" ] && \
  trash_gadgets_are_current && \
  kernel_security_config_ok; then
	echo "[+] Using existing kernel image linux-$KERNEL_VERSION/arch/x86/boot/bzImage."
else
	echo "[+] Building kernel (or refreshing its security configuration)..."
  make -C linux-$KERNEL_VERSION defconfig
  linux-$KERNEL_VERSION/scripts/config --file linux-$KERNEL_VERSION/.config \
    -e MODULES -e DEVTMPFS -e BLK_DEV_INITRD \
    -e NET_9P -e NET_9P_VIRTIO -e 9P_FS -e 9P_FS_POSIX_ACL -e 9P_FS_SECURITY \
    -e VIRTIO_PCI -e VIRTIO_BLK -e VIRTIO_NET -e VIRTIO_CONSOLE \
    -e HW_RANDOM_VIRTIO -e DRM_VIRTIO_GPU -e VIRTIO_PCI_LEGACY \
    -e VIRTIO_BALLOON -e VIRTIO_INPUT -e CRYPTO_DEV_VIRTIO \
    -e GDB_SCRIPTS -e DEBUG_FS -d DEBUG_INFO_NONE -e DEBUG_INFO_DWARF4 \
    -d DEBUG_INFO_BTF -d WERROR \
    -e INIT_STACK_NONE -d INIT_STACK_ALL_PATTERN -d INIT_STACK_ALL_ZERO \
    -d VMAP_STACK
  make -C linux-$KERNEL_VERSION olddefconfig
  # These boot stages reset KBUILD_CFLAGS and otherwise inherit GCC 15's
  # C23 default, which conflicts with the 6.8 kernel's bool/false definitions.
  sed -i 's/^KBUILD_CFLAGS[[:space:]]*:= $(subst /KBUILD_CFLAGS := -std=gnu11 $(subst /' \
    linux-$KERNEL_VERSION/drivers/firmware/efi/libstub/Makefile
  sed -i 's/^KBUILD_CFLAGS := -m$(BITS)/KBUILD_CFLAGS := -std=gnu11 -m$(BITS)/' \
    linux-$KERNEL_VERSION/arch/x86/boot/compressed/Makefile
  make -C linux-$KERNEL_VERSION -j"$JOBS" bzImage modules
  printf '%s\n' "$TRASH_GADGETS_HASH" > "${TRASH_GADGETS_STAMP}.part"
  mv -- "${TRASH_GADGETS_STAMP}.part" "$TRASH_GADGETS_STAMP"
fi
#
# Busybox
#

echo "[+] Downloading busybox..."
if [ ! -f busybox-$BUSYBOX_VERSION.tar.bz2 ]; then
  wget -c https://busybox.net/downloads/busybox-$BUSYBOX_VERSION.tar.bz2
else
  echo "[+] Using cached busybox-$BUSYBOX_VERSION.tar.bz2."
fi
[ -e busybox-$BUSYBOX_VERSION ] || tar xjf busybox-$BUSYBOX_VERSION.tar.bz2

echo "[+] Building busybox..."
make -C busybox-$BUSYBOX_VERSION defconfig
sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/g' busybox-$BUSYBOX_VERSION/.config
sed -i 's/^CONFIG_TC=y/# CONFIG_TC is not set/' busybox-$BUSYBOX_VERSION/.config
sed -i 's/^CONFIG_FEATURE_TC_INGRESS=y/# CONFIG_FEATURE_TC_INGRESS is not set/' busybox-$BUSYBOX_VERSION/.config
make -C busybox-$BUSYBOX_VERSION -j"$JOBS"
make -C busybox-$BUSYBOX_VERSION install

#
# filesystem
#

echo "[+] Building filesystem..."
mkdir -p "$ROOTFS_DIR"/{bin,sbin,etc,proc,sys,usr/bin,usr/sbin,root,home/ctf}
cp -a busybox-$BUSYBOX_VERSION/_install/. "$ROOTFS_DIR/"
gcc -static -Os -Wall -Wextra -o "$ROOTFS_DIR/usr/bin/sudo" "$MODULE_DIR/sudo.c"
install -m 0755 "$TOOLS_DIR/vm-insmod" "$ROOTFS_DIR/usr/bin/vm-insmod"
chmod +x "$ROOTFS_DIR/init"

#
# modules
#

echo "[+] Building modules..."
make -C "$MODULE_DIR" KERNEL_DIR="$BUILD_DIR/linux-$KERNEL_VERSION"
cp "$MODULE_DIR"/*.ko "$ROOTFS_DIR/"

echo "[+] Packaging runtime artifacts..."
install -m 0644 "linux-$KERNEL_VERSION/arch/x86/boot/bzImage" "$RUNTIME_KERNEL_IMAGE"
install -m 0644 "linux-$KERNEL_VERSION/vmlinux" "$RUNTIME_VMLINUX"
initramfs_part="$RUNTIME_INITRAMFS.part"
rm -f -- "$initramfs_part"
pushd "$ROOTFS_DIR" >/dev/null
find . -print0 | cpio --null -o --format=newc --owner=0:0 --quiet | gzip -9 > "$initramfs_part"
popd >/dev/null
mv -- "$initramfs_part" "$RUNTIME_INITRAMFS"
BUILD_DIR="$BUILD_DIR" bash "$SCRIPT_DIR/clean.sh" after-build
echo "[+] Build complete. Run ./launch.sh from $SCRIPT_DIR."
